version: '3.8'

services:
  task-runner:
    image: hummingbot/quants-lab:latest
    volumes:
      - .:/quants-lab
      - ./config:/quants-lab/config
    # env_file:
    #  - .env
    network_mode: host
    command: conda run --no-capture-output -n quants-lab python3 run_tasks.py --config ${TASK_CONFIG:-config/tasks.yml}
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "10" 
